### ISSUE TITLE
Custom validation functions - import ValidationGroup

### ISSUE THREAD

**Issue by stevies** [aurelia/validation#117]
import {ValidationGroup} from 'aurelia-validation' fails to import anything - ValidationGroup not exported from index.js

You can't then do:  
```
 ValidationGroup.prototype.SSN = function()
    {
      this.matches(/^[0-9]{3}\-?[0-9]{2}\-?[0-9]{4}$/)
          .withMessage((newValue, threshold) => {return `not a valid SSN`;});
      return this;
    }
``` 
Since ValidationGroup is undefined.

**Comment by stevies** [comment]
Edit title

**Comment by JoshHarris** [comment]
Yes, I am also much confused :)

**Comment by stevies** [comment]
It is easy enough to fix.  You need to modify file: jspm_packages\github\aurelia\validation@0.2.8\index.js
Add './validation/validation-group' to the define array, and add '_validationGroup' to the list of function arguments.  Eg:  
```
define(['exports', './validation/validation-config', './validation/validation', './validation/utilities', './validation/validation-locale',
  './validation/validation-result', './validation/validation-rules', './validation/validate-custom-attribute',
  './validation/validate-custom-attribute-view-strategy', './validation/decorators', './validation/validation-group'],
    function (exports, _validationValidationConfig, _validationValidation, _validationUtilities, _validationValidationLocale,
              _validationValidationResult, _validationValidationRules, _validationValidateCustomAttribute,
              _validationValidateCustomAttributeViewStrategy, _validationDecorators, _validationGroup) {
```
Then add 
```
  exports.ValidationGroup = _validationGroup.ValidationGroup;
```

**Comment by PWKad** [comment]
@stevies Is this fixed in the current release?  If not could you PR the fix you mentioned and a reproduction?

**Comment by stevies** [comment]
Not fixed, I'm afraid.  ValidationGroup is not being exported from index.js.  My fix above was just a temporary hack the built code inside the downloaded package. I'll try to put together a PR if you need it (and I can work out how to do it).  I think fix should be easy - just add:
```
export {ValidationGroup} from './validation/validation-group';
```
to index.js - something like that.  
You need to be able to import ValidationGroup to be able to add your own custom validation.  See:  https://github.com/aurelia/validation/blob/master/doc/Intro.md#custom-validation
