### ISSUE TITLE
Validation and @bindable don't get along

### ISSUE THREAD

**Issue by janvanderhaegen** [aurelia/validation#46]
When adding validation on an @bindable property, the validation encounters a stack-overflow...

**Comment by CharlesPockert** [comment]
Reproduced in skeleton:

```
import {computedFrom, inject, bindable} from 'aurelia-framework';
import { Validation } from 'aurelia-validation';

@inject(Validation)
export class Welcome{
  @bindable heading = 'Welcome to the Aurelia Navigation App!';
  firstName = 'John';
  lastName = 'Doe';

  constructor(validation) {
       // Validate the VM
        this.validation = validation.on(this)
            .ensure('heading')
            .isNotEmpty()
            .withMessage("please provide an email address")
            .isEmail();
  }
  //Getters can't be observed with Object.observe, so they must be dirty checked.
  //However, if you tell Aurelia the dependencies, it no longer needs to dirty check the property.
  //To optimize by declaring the properties that this getter is computed from, uncomment the line below.
  //@computedFrom('firstName', 'lastName')
  get fullName(){
    return `${this.firstName} ${this.lastName}`;
  }

  welcome(){
    alert(`Welcome, ${this.fullName}!`);
  }
}

export class UpperValueConverter {
  toView(value){
    return value && value.toUpperCase();
  }
}
```

**Comment by janvanderhaegen** [comment]
Ouch, this seems to be a bug in aurelia-binding (https://github.com/aurelia/binding/issues/89): it's not possible to get an observerlocator over an @bindable property unless that property is already resolved.
The team will fix this issue.
I've checked in a patch for the validation library: https://github.com/aurelia/validation/commit/a10a4db3972d857757cc3d142dea120cd1b00f6f
You can jspm install aurelia-validation=github:aurelia/validation@master to get this fix before we release 0.2.5, or you can use a workaround where you resolve the value from the @bindable property before adding validation:
``` javascript
constructor(validation) {
       var resolved = this.heading; // add this
        this.validation = validation.on(this)
            .ensure('heading')
```

**Comment by janvanderhaegen** [comment]
Can now be properly fixed after the aurelia-binding with this patch https://github.com/aurelia/binding/commit/f09451cefb79a85f14b47c89bf6e2c1fa0ac008e is released.

**Comment by mttmccb** [comment]
Any news on this? last time I check I was still getting errors.

**Comment by janvanderhaegen** [comment]
Need to recheck this. We had a workaround, going to see if it broke with the latest release :S

**Comment by EisenbergEffect** [comment]
@janvanderhaegen This should be fixed I believe. If it's not, let me know.

**Comment by janvanderhaegen** [comment]
Going to add this to the validation-examples so we have a live test. Will
let you know if we need input

2015-06-28 14:50 GMT-05:00 Rob Eisenberg <notifications@github.com>:
