### ISSUE TITLE
Type definition of getContextFor conflicts with aurelia-binding

### ISSUE THREAD

**Issue by vuorinem** [aurelia/validation#471]
**I'm submitting a bug report**

* **Library Version:**
1.1.2

* **Language:**
TypeScript 2.4 / 2.6

**Current behavior:**
When both aurelia-binding and aurelia-validation are used in the project, the build fails with the TypeScript error:
```
aurelia-validation@1.1.2\property-info.d.ts(3,11): error TS2451: Cannot redeclare block-scoped variable 'getContextFor'.
```

I assume this is because of the differences in the definition of getContextFor.

The type definition of getContextFor in property-info.d.ts:
https://github.com/aurelia/validation/blob/678911216e43b3ca130d9951012569aaba698f4e/src/property-info.ts#L12-L14

Definition in aurelia-binding:
https://github.com/aurelia/binding/blob/1d6e826dbbc401ca21ad0deaf7acca498cd71c8b/src/scope.js#L19
```
export function getContextFor(name: string, scope: Scope, ancestor: number): any {...}
```

Could this be fixed by replacing the type definition with this export?
```
export { getContextFor } from 'aurelia-binding';
```

**Comment by jdanyow** [comment]
I think a definition for `getContextFor` needs to be added to the [aurelia-binding.d.ts](https://github.com/aurelia/binding/blob/1d6e826dbbc401ca21ad0deaf7acca498cd71c8b/src/aurelia-binding.d.ts) file (it's hand written). Once that is released we could remove the `declare module 'aurelia-binding'...` in the validation code base.

**Comment by jdanyow** [comment]
fixed in https://github.com/aurelia/binding/commit/c7ab819bc144697c056f279a238861ca6c24c2e1

**Comment by Mobe91** [comment]
I am still facing this problem coming from `dist/amd/property-info.d.ts`. When is your change from 8d325e49abc7 going to be released?

**Comment by wpearson4** [comment]
I am facing the same problem as well and it is causing other issues during the compilation process.

**Comment by Mobe91** [comment]
Worked around it by locking the typings version for `aurelia-binding` in typings.json to an earlier version:
```
"aurelia-binding": "github:aurelia/binding#011eca0b418c20c70f5ed235b553ab0176b58013"
```

**Comment by wpearson4** [comment]
Thank you!!  It worked for me as well

**Comment by Krossmaskinen** [comment]
I have the same issue and the workaround from @Mobe91 works!

**Comment by wpearson4** [comment]
Has an updated been released for this.? I am still receiving an error after the latest updated.

**Comment by Alexander-Taran** [comment]
@wpearson4 you probably use npm and you have package.lock.json
delete that one and node_modules and reinstall dependencies.
there are no conflicting typings for latest versions of binding and validation

It was discussed a lot @ https://discourse.aurelia.io/
and in https://gitter.im/aurelia/Discuss

**Comment by wpearson4** [comment]
Thank you.  That did the trick
